import type { People, Film, Planet, Starship, ApiResponse } from "@/types"

// Mock data for Star Wars characters
const mockPeople: People[] = [
  {
    name: "Luke Skywalker",
    height: "172",
    mass: "77",
    hair_color: "blond",
    skin_color: "fair",
    eye_color: "blue",
    birth_year: "19BBY",
    gender: "male",
    homeworld: "https://swapi.dev/api/planets/1/",
    films: [
      "https://swapi.dev/api/films/1/",
      "https://swapi.dev/api/films/2/",
      "https://swapi.dev/api/films/3/",
      "https://swapi.dev/api/films/6/",
    ],
    species: [],
    vehicles: ["https://swapi.dev/api/vehicles/14/", "https://swapi.dev/api/vehicles/30/"],
    starships: ["https://swapi.dev/api/starships/12/", "https://swapi.dev/api/starships/22/"],
    created: "2014-12-09T13:50:51.644000Z",
    edited: "2014-12-20T21:17:56.891000Z",
    url: "https://swapi.dev/api/people/1/",
  },
  {
    name: "Leia Organa",
    height: "150",
    mass: "49",
    hair_color: "brown",
    skin_color: "light",
    eye_color: "brown",
    birth_year: "19BBY",
    gender: "female",
    homeworld: "https://swapi.dev/api/planets/2/",
    films: [
      "https://swapi.dev/api/films/1/",
      "https://swapi.dev/api/films/2/",
      "https://swapi.dev/api/films/3/",
      "https://swapi.dev/api/films/6/",
    ],
    species: [],
    vehicles: ["https://swapi.dev/api/vehicles/30/"],
    starships: [],
    created: "2014-12-10T15:20:09.791000Z",
    edited: "2014-12-20T21:17:50.315000Z",
    url: "https://swapi.dev/api/people/5/",
  },
  {
    name: "Han Solo",
    height: "180",
    mass: "80",
    hair_color: "brown",
    skin_color: "fair",
    eye_color: "brown",
    birth_year: "29BBY",
    gender: "male",
    homeworld: "https://swapi.dev/api/planets/22/",
    films: ["https://swapi.dev/api/films/1/", "https://swapi.dev/api/films/2/", "https://swapi.dev/api/films/3/"],
    species: [],
    vehicles: [],
    starships: ["https://swapi.dev/api/starships/10/", "https://swapi.dev/api/starships/22/"],
    created: "2014-12-10T16:49:14.582000Z",
    edited: "2014-12-20T21:17:50.334000Z",
    url: "https://swapi.dev/api/people/14/",
  },
  {
    name: "Darth Vader",
    height: "202",
    mass: "136",
    hair_color: "none",
    skin_color: "white",
    eye_color: "yellow",
    birth_year: "41.9BBY",
    gender: "male",
    homeworld: "https://swapi.dev/api/planets/1/",
    films: [
      "https://swapi.dev/api/films/1/",
      "https://swapi.dev/api/films/2/",
      "https://swapi.dev/api/films/3/",
      "https://swapi.dev/api/films/6/",
    ],
    species: [],
    vehicles: [],
    starships: ["https://swapi.dev/api/starships/13/"],
    created: "2014-12-10T15:18:20.704000Z",
    edited: "2014-12-20T21:17:50.313000Z",
    url: "https://swapi.dev/api/people/4/",
  },
  {
    name: "Obi-Wan Kenobi",
    height: "182",
    mass: "77",
    hair_color: "auburn, white",
    skin_color: "fair",
    eye_color: "blue-gray",
    birth_year: "57BBY",
    gender: "male",
    homeworld: "https://swapi.dev/api/planets/20/",
    films: [
      "https://swapi.dev/api/films/1/",
      "https://swapi.dev/api/films/2/",
      "https://swapi.dev/api/films/3/",
      "https://swapi.dev/api/films/4/",
      "https://swapi.dev/api/films/5/",
      "https://swapi.dev/api/films/6/",
    ],
    species: [],
    vehicles: ["https://swapi.dev/api/vehicles/38/"],
    starships: [
      "https://swapi.dev/api/starships/48/",
      "https://swapi.dev/api/starships/59/",
      "https://swapi.dev/api/starships/64/",
      "https://swapi.dev/api/starships/65/",
      "https://swapi.dev/api/starships/74/",
    ],
    created: "2014-12-10T16:16:29.192000Z",
    edited: "2014-12-20T21:17:50.325000Z",
    url: "https://swapi.dev/api/people/10/",
  },
  {
    name: "Yoda",
    height: "66",
    mass: "17",
    hair_color: "white",
    skin_color: "green",
    eye_color: "brown",
    birth_year: "896BBY",
    gender: "male",
    homeworld: "https://swapi.dev/api/planets/28/",
    films: [
      "https://swapi.dev/api/films/2/",
      "https://swapi.dev/api/films/3/",
      "https://swapi.dev/api/films/4/",
      "https://swapi.dev/api/films/5/",
      "https://swapi.dev/api/films/6/",
    ],
    species: ["https://swapi.dev/api/species/6/"],
    vehicles: [],
    starships: [],
    created: "2014-12-15T12:26:01.042000Z",
    edited: "2014-12-20T21:17:50.345000Z",
    url: "https://swapi.dev/api/people/20/",
  },
  {
    name: "Chewbacca",
    height: "228",
    mass: "112",
    hair_color: "brown",
    skin_color: "unknown",
    eye_color: "blue",
    birth_year: "200BBY",
    gender: "male",
    homeworld: "https://swapi.dev/api/planets/14/",
    films: [
      "https://swapi.dev/api/films/1/",
      "https://swapi.dev/api/films/2/",
      "https://swapi.dev/api/films/3/",
      "https://swapi.dev/api/films/6/",
    ],
    species: ["https://swapi.dev/api/species/3/"],
    vehicles: ["https://swapi.dev/api/vehicles/19/"],
    starships: ["https://swapi.dev/api/starships/10/", "https://swapi.dev/api/starships/22/"],
    created: "2014-12-10T16:42:45.066000Z",
    edited: "2014-12-20T21:17:50.332000Z",
    url: "https://swapi.dev/api/people/13/",
  },
  {
    name: "R2-D2",
    height: "96",
    mass: "32",
    hair_color: "n/a",
    skin_color: "white, blue",
    eye_color: "red",
    birth_year: "33BBY",
    gender: "n/a",
    homeworld: "https://swapi.dev/api/planets/8/",
    films: [
      "https://swapi.dev/api/films/1/",
      "https://swapi.dev/api/films/2/",
      "https://swapi.dev/api/films/3/",
      "https://swapi.dev/api/films/4/",
      "https://swapi.dev/api/films/5/",
      "https://swapi.dev/api/films/6/",
    ],
    species: ["https://swapi.dev/api/species/2/"],
    vehicles: [],
    starships: [],
    created: "2014-12-10T15:11:50.376000Z",
    edited: "2014-12-20T21:17:50.311000Z",
    url: "https://swapi.dev/api/people/3/",
  },
]

const mockFilms: { [key: string]: Film } = {
  "https://swapi.dev/api/films/1/": {
    title: "A New Hope",
    episode_id: 4,
    opening_crawl: "It is a period of civil war...",
    director: "George Lucas",
    producer: "Gary Kurtz, Rick McCallum",
    release_date: "1977-05-25",
    characters: [],
    planets: [],
    starships: [],
    vehicles: [],
    species: [],
    created: "2014-12-10T14:23:31.880000Z",
    edited: "2014-12-20T19:49:45.256000Z",
    url: "https://swapi.dev/api/films/1/",
  },
  "https://swapi.dev/api/films/2/": {
    title: "The Empire Strikes Back",
    episode_id: 5,
    opening_crawl: "It is a dark time for the Rebellion...",
    director: "Irvin Kershner",
    producer: "Gary Kurtz, Rick McCallum",
    release_date: "1980-05-17",
    characters: [],
    planets: [],
    starships: [],
    vehicles: [],
    species: [],
    created: "2014-12-12T11:26:24.656000Z",
    edited: "2014-12-15T13:07:53.386000Z",
    url: "https://swapi.dev/api/films/2/",
  },
  "https://swapi.dev/api/films/3/": {
    title: "Return of the Jedi",
    episode_id: 6,
    opening_crawl: "Luke Skywalker has returned to his home planet...",
    director: "Richard Marquand",
    producer: "Howard G. Kazanjian, George Lucas, Rick McCallum",
    release_date: "1983-05-25",
    characters: [],
    planets: [],
    starships: [],
    vehicles: [],
    species: [],
    created: "2014-12-18T10:39:33.255000Z",
    edited: "2014-12-20T09:48:37.462000Z",
    url: "https://swapi.dev/api/films/3/",
  },
  "https://swapi.dev/api/films/4/": {
    title: "The Phantom Menace",
    episode_id: 1,
    opening_crawl: "Turmoil has engulfed the Galactic Republic...",
    director: "George Lucas",
    producer: "Rick McCallum",
    release_date: "1999-05-19",
    characters: [],
    planets: [],
    starships: [],
    vehicles: [],
    species: [],
    created: "2014-12-19T16:52:55.740000Z",
    edited: "2014-12-20T10:54:07.216000Z",
    url: "https://swapi.dev/api/films/4/",
  },
  "https://swapi.dev/api/films/5/": {
    title: "Attack of the Clones",
    episode_id: 2,
    opening_crawl: "There is unrest in the Galactic Senate...",
    director: "George Lucas",
    producer: "Rick McCallum",
    release_date: "2002-05-16",
    characters: [],
    planets: [],
    starships: [],
    vehicles: [],
    species: [],
    created: "2014-12-20T10:57:57.886000Z",
    edited: "2014-12-20T20:18:48.516000Z",
    url: "https://swapi.dev/api/films/5/",
  },
  "https://swapi.dev/api/films/6/": {
    title: "Revenge of the Sith",
    episode_id: 3,
    opening_crawl: "War! The Republic is crumbling...",
    director: "George Lucas",
    producer: "Rick McCallum",
    release_date: "2005-05-19",
    characters: [],
    planets: [],
    starships: [],
    vehicles: [],
    species: [],
    created: "2014-12-20T18:49:38.403000Z",
    edited: "2014-12-20T20:47:52.073000Z",
    url: "https://swapi.dev/api/films/6/",
  },
}

const mockPlanets: { [key: string]: Planet } = {
  "https://swapi.dev/api/planets/1/": {
    name: "Tatooine",
    rotation_period: "23",
    orbital_period: "304",
    diameter: "10465",
    climate: "arid",
    gravity: "1 standard",
    terrain: "desert",
    surface_water: "1",
    population: "200000",
    residents: [],
    films: [],
    created: "2014-12-09T13:50:49.641000Z",
    edited: "2014-12-20T20:58:18.411000Z",
    url: "https://swapi.dev/api/planets/1/",
  },
  "https://swapi.dev/api/planets/2/": {
    name: "Alderaan",
    rotation_period: "24",
    orbital_period: "364",
    diameter: "12500",
    climate: "temperate",
    gravity: "1 standard",
    terrain: "grasslands, mountains",
    surface_water: "40",
    population: "2000000000",
    residents: [],
    films: [],
    created: "2014-12-10T11:35:48.479000Z",
    edited: "2014-12-20T20:58:18.420000Z",
    url: "https://swapi.dev/api/planets/2/",
  },
  "https://swapi.dev/api/planets/8/": {
    name: "Naboo",
    rotation_period: "26",
    orbital_period: "312",
    diameter: "12120",
    climate: "temperate",
    gravity: "1 standard",
    terrain: "grassy hills, swamps, forests, mountains",
    surface_water: "12",
    population: "4500000000",
    residents: [],
    films: [],
    created: "2014-12-10T11:52:31.066000Z",
    edited: "2014-12-20T20:58:18.430000Z",
    url: "https://swapi.dev/api/planets/8/",
  },
  "https://swapi.dev/api/planets/14/": {
    name: "Kashyyyk",
    rotation_period: "26",
    orbital_period: "381",
    diameter: "12765",
    climate: "tropical",
    gravity: "1 standard",
    terrain: "jungle, forests, lakes, rivers",
    surface_water: "60",
    population: "45000000",
    residents: [],
    films: [],
    created: "2014-12-10T13:32:00.124000Z",
    edited: "2014-12-20T20:58:18.442000Z",
    url: "https://swapi.dev/api/planets/14/",
  },
  "https://swapi.dev/api/planets/20/": {
    name: "Stewart",
    rotation_period: "unknown",
    orbital_period: "unknown",
    diameter: "0",
    climate: "frigid",
    gravity: "1 standard",
    terrain: "asteroid",
    surface_water: "unknown",
    population: "unknown",
    residents: [],
    films: [],
    created: "2014-12-10T16:16:26.566000Z",
    edited: "2014-12-20T20:58:18.452000Z",
    url: "https://swapi.dev/api/planets/20/",
  },
  "https://swapi.dev/api/planets/22/": {
    name: "Corellia",
    rotation_period: "25",
    orbital_period: "329",
    diameter: "11000",
    climate: "temperate",
    gravity: "1 standard",
    terrain: "plains, urban, hills, forests",
    surface_water: "70",
    population: "3000000000",
    residents: [],
    films: [],
    created: "2014-12-10T16:49:12.453000Z",
    edited: "2014-12-20T20:58:18.456000Z",
    url: "https://swapi.dev/api/planets/22/",
  },
  "https://swapi.dev/api/planets/28/": {
    name: "Dagobah",
    rotation_period: "23",
    orbital_period: "341",
    diameter: "8900",
    climate: "murky",
    gravity: "N/A",
    terrain: "swamp, jungles",
    surface_water: "8",
    population: "unknown",
    residents: [],
    films: [],
    created: "2014-12-10T18:42:22.590000Z",
    edited: "2014-12-20T20:58:18.425000Z",
    url: "https://swapi.dev/api/planets/28/",
  },
}

const mockStarships: { [key: string]: Starship } = {
  "https://swapi.dev/api/starships/10/": {
    name: "Millennium Falcon",
    model: "YT-1300 light freighter",
    manufacturer: "Corellian Engineering Corporation",
    cost_in_credits: "100000",
    length: "34.37",
    max_atmosphering_speed: "1050",
    crew: "4",
    passengers: "6",
    cargo_capacity: "100000",
    consumables: "2 months",
    hyperdrive_rating: "0.5",
    MGLT: "75",
    starship_class: "Light freighter",
    pilots: [],
    films: [],
    created: "2014-12-10T16:59:45.094000Z",
    edited: "2014-12-20T21:23:49.880000Z",
    url: "https://swapi.dev/api/starships/10/",
  },
  "https://swapi.dev/api/starships/12/": {
    name: "X-wing",
    model: "T-65 X-wing",
    manufacturer: "Incom Corporation",
    cost_in_credits: "149999",
    length: "12.5",
    max_atmosphering_speed: "1050",
    crew: "1",
    passengers: "0",
    cargo_capacity: "110",
    consumables: "1 week",
    hyperdrive_rating: "1.0",
    MGLT: "100",
    starship_class: "Starfighter",
    pilots: [],
    films: [],
    created: "2014-12-12T11:19:05.340000Z",
    edited: "2014-12-20T21:23:49.886000Z",
    url: "https://swapi.dev/api/starships/12/",
  },
  "https://swapi.dev/api/starships/13/": {
    name: "TIE Advanced x1",
    model: "Twin Ion Engine Advanced x1",
    manufacturer: "Sienar Fleet Systems",
    cost_in_credits: "unknown",
    length: "9.2",
    max_atmosphering_speed: "1200",
    crew: "1",
    passengers: "0",
    cargo_capacity: "150",
    consumables: "5 days",
    hyperdrive_rating: "1.0",
    MGLT: "105",
    starship_class: "Starfighter",
    pilots: [],
    films: [],
    created: "2014-12-12T11:21:32.991000Z",
    edited: "2014-12-20T21:23:49.889000Z",
    url: "https://swapi.dev/api/starships/13/",
  },
  "https://swapi.dev/api/starships/22/": {
    name: "Imperial shuttle",
    model: "Lambda-class T-4a shuttle",
    manufacturer: "Sienar Fleet Systems",
    cost_in_credits: "240000",
    length: "20",
    max_atmosphering_speed: "850",
    crew: "6",
    passengers: "20",
    cargo_capacity: "80000",
    consumables: "2 months",
    hyperdrive_rating: "1.0",
    MGLT: "50",
    starship_class: "Armed government transport",
    pilots: [],
    films: [],
    created: "2014-12-15T13:04:47.235000Z",
    edited: "2014-12-20T21:23:49.900000Z",
    url: "https://swapi.dev/api/starships/22/",
  },
}

export async function fetchPeople(page = 1): Promise<ApiResponse<People>> {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 500))

  const itemsPerPage = 10
  const startIndex = (page - 1) * itemsPerPage
  const endIndex = startIndex + itemsPerPage
  const paginatedResults = mockPeople.slice(startIndex, endIndex)

  return {
    count: mockPeople.length,
    next: endIndex < mockPeople.length ? `page=${page + 1}` : null,
    previous: page > 1 ? `page=${page - 1}` : null,
    results: paginatedResults,
  }
}

export async function fetchPerson(id: string): Promise<People> {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 300))

  const person = mockPeople.find((p) => getIdFromUrl(p.url) === id)
  if (!person) {
    throw new Error("Person not found")
  }
  return person
}

export async function fetchFilm(url: string): Promise<Film> {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 200))

  const film = mockFilms[url]
  if (!film) {
    throw new Error("Film not found")
  }
  return film
}

export async function fetchPlanet(url: string): Promise<Planet> {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 200))

  const planet = mockPlanets[url]
  if (!planet) {
    throw new Error("Planet not found")
  }
  return planet
}

export async function fetchStarship(url: string): Promise<Starship> {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 200))

  const starship = mockStarships[url]
  if (!starship) {
    throw new Error("Starship not found")
  }
  return starship
}

export function getIdFromUrl(url: string): string {
  const matches = url.match(/\/(\d+)\/$/)
  return matches ? matches[1] : ""
}
